Repository redBorder/cookbook-rb-cep, pull requests merged in 2024-06, with the labels that each got.

#3 fix curl
  resources/providers/config.rb
Labels: kind/bug, size/L

#6 Improvement/fix lint
  resources/attributes/default.rb
  resources/libraries/helper.rb
  resources/providers/config.rb
  resources/recipes/default.rb
  resources/resources/config.rb
Labels: enhancement, kind/bug, size/L, lint, refactor

#7 Release 0.0.2
  .github/workflows/rpm.yml
  CHANGELOG.md
  README.md
  resources/attributes/default.rb
  resources/libraries/helper.rb
  resources/metadata.rb
  resources/providers/config.rb
  resources/recipes/default.rb
  resources/resources/config.rb
Labels: size/L, kind/documentation

#8 Bugfix/#16798 redborder cep user does not exist
  resources/providers/config.rb
Labels: kind/bug, size/S
